authors: []
blacklist: []
build_space: build
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist:
- doosan_robot
- doosan_robotics
- dsr_control
- dsr_description
- dsr_example_py
- dsr_gazebo
- dsr_launcher
- dsr_msgs
- moveit_config_a0509
- moveit_config_a0912
- moveit_config_h2017
- moveit_config_h2515
- moveit_config_m0609
- moveit_config_m0617
- moveit_config_m1013
- moveit_config_m1509
- serial
- azure_kinect_ros_driver
- cleaning
